### ISSUE TITLE
Ability to upload multiple/all project files in one go

### ISSUE THREAD

**Issue by balva** [PeterStaev/lego-spikeprime-mindstorms-vscode#13]
Essential for working with larger code bases. This would be a major differentiation from the stock Prime App workflow. Inspired by the ev3dev extension for the last gen EV3 bricks (https://marketplace.visualstudio.com/items?itemName=ev3dev.ev3dev-browser)

**Comment by PeterStaev** [comment]
Hey @balva , that would be a good improvement, but I'm not sure if the new bricks support multiple files in a project 😞

**Comment by azzieg** [comment]
For what it is worth, programs sent to my hub now include a filename :-)

```
{
  "i":"RNd-",
  "m":"start_write_program",
  "p":{
    "meta":{
      "created":1663500597447,
      "modified":1664662362313,
      "project_id":"8e6_GMi87A-_",
      "name":"UHJvamVrdCA0",
      "type":"scratch"
    },
    "size":406,
    "slotid":0,
    "filename":"__init__.mpy"
  }
}
```
