### ISSUE TITLE
ChromeOS/Chromebook support?

### ISSUE THREAD

**Issue by ws1088** [PeterStaev/lego-spikeprime-mindstorms-vscode#25]
I was trying the linux container in ChromeOS and installed vscode. The lego extension installed without errors but the extension does not show up on the bottom status bar and running the command(s) would give:

![image](https://user-images.githubusercontent.com/3947543/140623694-11e4ed61-f342-418d-80aa-c43bf84e187c.png)

**Comment by PeterStaev** [comment]
@ws1088 , this because the native bindings used to communicate over serial are not compatible with the linux version/container you are using. You have to download the source of the plugin and rebuild the bindings for your environment.
