### ISSUE TITLE
Connecting to Hub Failed! Opening COM8: File not found

### ISSUE THREAD

**Issue by ArshadIram** [PeterStaev/lego-spikeprime-mindstorms-vscode#30]
Hello, 

I am using this plugin and while connecting it with the minestrone hub I am facing this error "Connecting to Hub Failed! Opening COM8: File not found". Can you please help me in solving this issue?

**Comment by PeterStaev** [comment]
Hey @ArshadIram , usually this indicates you are using a wrong COM port to connect. Make sure you are connecting to the right one where the hub is plugged in.

**Comment by ArshadIram** [comment]
Yes, thank you so much. It got fixed
