### ISSUE TITLE
Cannot connect Lego Hub

### ISSUE THREAD

**Issue by kaalen** [PeterStaev/lego-spikeprime-mindstorms-vscode#35]
This extension doesn't seem to work for me. Is it supposed to be "plug and play"?
I don't see any connection status in the bottom status bar.
I tried both USB cable and Bluetooth.
If I try to activate "Lego Hub: Connect to hub" via Command Palette, I get the following error
![image](https://user-images.githubusercontent.com/4881407/162860293-34ab98fa-46c6-45dc-a46a-554fff0ae055.png)

**Comment by PeterStaev** [comment]
@kaalen make sure you are using the latest version (1.6) of the extension and also latest version of vscode (1.66). If you still do not see the status bar item, let me know what OS you are using it on.

**Comment by PeterStaev** [comment]
Actually I just updated the plugin and it does not load :( Not sure what messed up the version uploaded to the extension gallery. Will see to adjust and push another version when possible.

**Comment by PeterStaev** [comment]
@kaalen please try version 1.6.1 of the extension. It should resolve the load problem.

**Comment by kaalen** [comment]
Confirming it now works. Great work, thanks for your effort. Coding in VSCode is much nicer than the LEGO app.
