### ISSUE TITLE
How to make the program exit after it's finished

### ISSUE THREAD

**Issue by BlockOG** [PeterStaev/lego-spikeprime-mindstorms-vscode#43]

**Comment by PeterStaev** [comment]
@BlockOG , you can use:
```python
raise SystemExit
```

**Comment by BlockOG** [comment]
But that shows an error on it, which I don't want

**Comment by PeterStaev** [comment]
I understand. Well, I'm not familiar with any other way to do it. Let's see if someone else has any ideas.

**Comment by BlockOG** [comment]
If the program is in advanced you can do
```py
vm.stop()
```
