### ISSUE TITLE
Importing self made modules.

### ISSUE THREAD

**Issue by JonathanDrukker** [PeterStaev/lego-spikeprime-mindstorms-vscode#45]
I'd like to import my own modules but every time I do it raises this error: ` ImportError: no module named 'TestModule'
`. I checked the name of the module and it matches all up.
`Main.py` is located in the same folder/directory as `TestModule.py`. Does anyone have a solution? Thanks

**Comment by PeterStaev** [comment]
@JonathanDrukker , you can't import your modules, since those modules are not present on the brick. Programs should be single file only. #3 might help with this since it will allow you to upload your module files to the brick. But I havent' researched yet, if this is supported.

**Comment by JonathanDrukker** [comment]
Thanks a lot, it was my prediction, I wasn't sure.
