### ISSUE TITLE
automatic saving in slot

### ISSUE THREAD

**Issue by legotronic** [PeterStaev/lego-spikeprime-mindstorms-vscode#48]
Very good AddOn for connecting the SPIKE hardware with VSC. 😎👌

One observation:
I can no longer select in which memory slot the source should be loaded - this happens "automatically" - with an added note in which slot the source has been stored in the program header.

How can I change this back to "manual selection"?

I have the same behavior on three computers.

**Comment by PeterStaev** [comment]
Hey @legotronic , if you want manual selection then you have to remove the added comment header at the top of the file.

**Comment by legotronic** [comment]
> Hey @legotronic , if you want manual selection then you have to remove the added comment header at the top of the file.

That's not true...? 😆

Ok - we will check this tomorrow.

and thanks for the quick feedback.
