### ISSUE TITLE
List more advanced features :-)

### ISSUE THREAD

**Issue by azzieg** [PeterStaev/lego-spikeprime-mindstorms-vscode#49]
I was thinking of a web-based IDE for Mindstorms (similar to Pybricks Code, but for original firmware) and encountered your project. Very impressive!

You might want to list more features of the advanced API. I have decoded pretty much all interesting word blocks, I think it should be a good resource for finding out what's possible: https://github.com/azzieg/mindstorms-inventor/tree/main/word_blocks  Or maybe just link to my GitHub repo from your ADVANCED-FEATURES.md or README.md? ;-)

**Comment by PeterStaev** [comment]
Thanks @azzieg ! Impressive work! Added a link to your repo.
