### ISSUE TITLE
Bluetooth not showing up on windows 10

### ISSUE THREAD

**Issue by Ultra980** [PeterStaev/lego-spikeprime-mindstorms-vscode#50]
When I try to connect to the spike prime (either via the command pallette, or the button on the bottom), only the COM ports show up. How do I connect through bluetooth?

**Comment by PeterStaev** [comment]
Hey @Ultra980 , even the LEGO software connects to the brick via the create COM port when you connect the brick over BLE to the computer. So you need to find the port to which the brick connected over BLE and use that one.

**Comment by Ultra980** [comment]
None of the COM ports work...

**Comment by PeterStaev** [comment]
Try connecting the brick using the LEGO software first, then try using the plugin.

**Comment by PeterStaev** [comment]
No further input to this so going to close it.
