### ISSUE TITLE
FLL Coach here (not an actual "issue")

### ISSUE THREAD

**Issue by MrGibbage** [PeterStaev/lego-spikeprime-mindstorms-vscode#52]
Hello Peter. I thought you might be interested to know how I use your plugin. I am an FLL coach and we used your plugin all season, and it worked perfectly. Middle school kids were able to pick up the coding in no time at all. We advanced past our qualifier and did pretty good at our regioal championship (VA-DC).

I guess if anything that I could ask of you is, do you know a good online place where FLL coaches using Python on the Spike Prime hangout? I'd love to see how other coaches are doing this, and what kinds of cool programs they have written.

Anyway, sorry to hijack your support issues here, but please keep up the great work!

Skip Morrow
Coach Team 24277

**Comment by PeterStaev** [comment]
Hey @MrGibbage , thanks for the kind words 😄  Glad that this plugin is helping you in your job as well as the kids you are teaching!

Sadly I'm not a coach myself and do not know of any FLL specific groups.
