### ISSUE TITLE
Is it works?

### ISSUE THREAD

**Issue by JaeYoungLee79** [PeterStaev/lego-spikeprime-mindstorms-vscode#53]
Dear Sir
1) Install Extension v1.6.1
2) And next? what am I to do?
Your explain :
"Clicking on the status will either connect or disconnect (if already connected). Support connecting to USB and Bluetooth (see Known Issues for limitations)."

Where is this?

**Comment by PeterStaev** [comment]
Hey @JaeYoungLee79 , in vscode status bar you should have section for the connection (it is visible in the first screenshot in the readme). Also you can use vscode command palette to perform various actions with the extension. Simply press F1 and search for "LEGO".

**Comment by PeterStaev** [comment]
No further input to this so will close it.
