### ISSUE TITLE
question about usage

### ISSUE THREAD

**Issue by takumaoda** [PeterStaev/lego-spikeprime-mindstorms-vscode#56]
Hello.
I am a Japanese student.
I would very much like to use this extension, but I did not understand how to use it. Could you please tell me how to connect to the hub?

**Comment by PeterStaev** [comment]
Hey @takumaoda , have you checked the readme? It explains how you should work with the plugin (connection, running programs, etc.). Also if you open vscode command palette (usually done by pressing F1), you could type `LEGO` and you will see all the commands the extension exponses. Selecting a command should guide you through the process.

**Comment by PeterStaev** [comment]
No further input to this, so I'm going to close it.
