### ISSUE TITLE
spike prime new os connect

### ISSUE THREAD

**Issue by ksjzang** [PeterStaev/lego-spikeprime-mindstorms-vscode#60]
I'm using this function too well. As you know, Spike Prime's hub os has been updated to 1.3.26, but I don't think I've been able to connect to VSCODE since then. I wonder if there is an update scheduled. Or is there a way for me to set up or take action separately?

**Comment by PeterStaev** [comment]
Hey @ksjzang , this is a known issue. Currently the plugin supports only HubOS2. There are some big changes to HubOS 3 communication that are preventing the plugin to communicate with the brick (LEGO only recently added support for Python to HubOS3). 

I do not have any ETA as I do not want to update my MINDSTORMS brick to the new OS, as the MINDSTORMS app will probably not support connecting to it. 

You can subscribe to #55 to monitor for progress on this matter.
