### ISSUE TITLE
Extension creates *.assembled.py file

### ISSUE THREAD

**Issue by Ruimtewese** [PeterStaev/lego-spikeprime-mindstorms-vscode#62]
@PeterStaev , at runtime the extension creates an *.assembled.py file. Is this normal or again some setting I should have ticked somewhere in VSC?

![image](https://github.com/PeterStaev/lego-spikeprime-mindstorms-vscode/assets/153099609/58ba1d2d-2d0c-46a8-b508-c3873e3a5fc7)

**Comment by PeterStaev** [comment]
@Ruimtewese yes, this is normal. It is part of the feature to allow you to use multi-file projects. On upload of the main program file the extension bundles all local files that are imported and adds them to the main file. 

You can check [here](https://github.com/PeterStaev/lego-spikeprime-mindstorms-vscode?tab=readme-ov-file#preprocessor) to see what syntax is currently supported. 

You can safely add those files in `.gitignore` or similar as they are regenerated every time the main program file is uploaded to the hub.
