### ISSUE TITLE
Add support for Linux platform

### ISSUE THREAD

**Issue by PeterStaev** [PeterStaev/lego-spikeprime-mindstorms-vscode#8]
Currently because there are no bindings for the linux platform the plugin fails with "Command not found" error. 

cc @tmechen

**Comment by PeterStaev** [comment]
Hey @tmechen, 

If I would appreciate if you can help with this, since I'm not much of a Linux guy :) You can check my explanation how to create the required bindings and submit a PR with them here: https://github.com/PeterStaev/lego-spikeprime-mindstorms-vscode/issues/4#issuecomment-857440080 The only change would be that the folder in which you should place the file is `node-v87-linux-x64`

**Comment by tmechen** [comment]
sry for not including in my initial comment:  
already tried building it, but got tons of warnings and didnt work first try, 
will look again later when not at work :)
